/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sadproject;

/**
 *
 * @author Homepc
 */
public class Guides extends javax.swing.JFrame {

    /**
     * Creates new form Guides
     */
    public Guides() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Submit = new javax.swing.JButton();
        Budget = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Eksan = new javax.swing.JLabel();
        Minhaj = new javax.swing.JLabel();
        Title1 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(625, 400));
        getContentPane().setLayout(null);

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(490, 330, 73, 23);

        Budget.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Budget.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Budget.setText("Budget Unavailable");
        getContentPane().add(Budget);
        Budget.setBounds(424, 300, 140, 17);

        jLayeredPane1.setLayout(new java.awt.GridLayout());

        Eksan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Eksan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Eksan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Homepc\\Downloads\\08.jpg")); // NOI18N
        Eksan.setText("Eksan");
        Eksan.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3)));
        Eksan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EksanMouseClicked(evt);
            }
        });
        jLayeredPane1.add(Eksan);

        Minhaj.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Minhaj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Minhaj.setIcon(new javax.swing.ImageIcon("C:\\Users\\Homepc\\Downloads\\07.jpg")); // NOI18N
        Minhaj.setText("Minhaj");
        Minhaj.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3)));
        Minhaj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinhajMouseClicked(evt);
            }
        });
        jLayeredPane1.add(Minhaj);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 94, 610, 180);

        Title1.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        Title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title1.setText("EASY TOUR");
        getContentPane().add(Title1);
        Title1.setBounds(-3, 50, 610, 41);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sadproject/bg3.jpg"))); // NOI18N
        getContentPane().add(BG);
        BG.setBounds(0, 0, 610, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EksanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EksanMouseClicked
        // TODO add your handling code here:
        SADProject.Guide=1;
        Budget.setText("1000 Tk");
        SADProject.GuideBudget=1000;
    }//GEN-LAST:event_EksanMouseClicked

    private void MinhajMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinhajMouseClicked
        // TODO add your handling code here:
        SADProject.Guide=2;
        Budget.setText("900 Tk");
        SADProject.GuideBudget=900;
    }//GEN-LAST:event_MinhajMouseClicked

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guides.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guides.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guides.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guides.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guides().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Budget;
    private javax.swing.JLabel Eksan;
    private javax.swing.JLabel Minhaj;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel Title1;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
