/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sadproject;

/**
 *
 * @author Homepc
 */
public class MainMenu extends javax.swing.JFrame {
    
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Pay = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Places = new javax.swing.JButton();
        Transport = new javax.swing.JButton();
        Guide = new javax.swing.JButton();
        Hotel = new javax.swing.JButton();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        Title.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("EASY TOUR");
        getContentPane().add(Title);
        Title.setBounds(-3, 50, 610, 41);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("LogOut");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(484, 30, 80, 20);

        Pay.setText("Checkout");
        Pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayActionPerformed(evt);
            }
        });
        getContentPane().add(Pay);
        Pay.setBounds(230, 290, 150, 23);

        jLayeredPane1.setLayout(new java.awt.FlowLayout());

        Places.setText("Places");
        Places.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlacesActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Places);

        Transport.setText("Transport");
        Transport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransportActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Transport);

        Guide.setText("Guide");
        Guide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuideActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Guide);

        Hotel.setText("Hotel");
        Hotel.setEnabled(false);
        jLayeredPane1.add(Hotel);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 190, 600, 50);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sadproject/bg.jpg"))); // NOI18N
        BG.setText("jLabel2");
        BG.setMaximumSize(new java.awt.Dimension(600, 400));
        BG.setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().add(BG);
        BG.setBounds(0, 0, 600, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlacesActionPerformed
        // TODO add your handling code here:
        if(SADProject.CurrentType==1){
            Places pp = new Places();
            pp.setVisible(true);
        }
        else{
            NewPlace np = new NewPlace();
            np.setVisible(true);
        }
        
    }//GEN-LAST:event_PlacesActionPerformed

    private void PayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayActionPerformed
        // TODO add your handling code here:
        Checkout co = new Checkout();
        co.setVisible(true);
        JDBCConnection.Checkout(JDBCConnection.SearchPlaceID(SADProject.ChosenPlace), SADProject.Guide,SADProject.totalBudget,SADProject.CurrentUsername);
    }//GEN-LAST:event_PayActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        SADProject.mm.setVisible(false);
        SADProject.lw.setVisible(true);
        SADProject.CurrentUsername="";
        SADProject.CurrentType=0;
    }//GEN-LAST:event_jLabel1MouseClicked

    private void TransportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransportActionPerformed
        // TODO add your handling code here:
        if(SADProject.CurrentType==1){
            Transport pp = new Transport();
            pp.setVisible(true);
        }
        else{
            NewTransport np = new NewTransport();
            np.setVisible(true);
        }
    }//GEN-LAST:event_TransportActionPerformed

    private void GuideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuideActionPerformed
        // TODO add your handling code here:
        Guides gd = new Guides();
        gd.setVisible(true);
        
    }//GEN-LAST:event_GuideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton Guide;
    private javax.swing.JButton Hotel;
    private javax.swing.JButton Pay;
    private javax.swing.JButton Places;
    private javax.swing.JLabel Title;
    private javax.swing.JButton Transport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
