/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sadproject;

/**
 *
 * @author Homepc
 */
public class Places extends javax.swing.JFrame {
    String _division ="";
    String _district ="";
    String _places ="";
    /**
     * Creates new form Places
     */
    public Places() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        View = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        Division = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        District = new javax.swing.JTextField();
        division = new javax.swing.JLabel();
        district = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Place = new javax.swing.JTextField();
        place = new javax.swing.JLabel();
        PlaceDescription = new javax.swing.JLabel();
        Select = new javax.swing.JButton();
        Title1 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        View.setText("View All Places");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });
        getContentPane().add(View);
        View.setBounds(0, 320, 600, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Select Division: ");

        Division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisionActionPerformed(evt);
            }
        });
        Division.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DivisionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DivisionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DivisionKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Select District: ");

        District.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistrictActionPerformed(evt);
            }
        });
        District.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DistrictKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Select Place: ");

        Place.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaceActionPerformed(evt);
            }
        });
        Place.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PlaceKeyReleased(evt);
            }
        });

        Select.setText("Select");
        Select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Division, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(District, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(division, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(district, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Place, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(place, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(PlaceDescription, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Select, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PlaceDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(36, 36, 36)
                                .addComponent(Division, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(District, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Place, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(division, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(district, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(place, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))))
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Select, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(262, 262, 262))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Division, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(division))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(District, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(district))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(place, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(Place, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(PlaceDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Select))
        );

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 110, 600, 190);

        Title1.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        Title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title1.setText("EASY TOUR");
        getContentPane().add(Title1);
        Title1.setBounds(-3, 50, 610, 41);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sadproject/bg.jpg"))); // NOI18N
        getContentPane().add(BG);
        BG.setBounds(0, 0, 600, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DivisionActionPerformed

    private void DistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DistrictActionPerformed

    private void PlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlaceActionPerformed

    private void DivisionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DivisionKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_DivisionKeyPressed

    private void DistrictKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DistrictKeyTyped
        // TODO add your handling code here:
        district.setText(JDBCConnection.SearchDistrict(District.getText(),division.getText()));
        if(!"".equals(district.getText())){
            Place.setEnabled(true);
        }
        else{
            //Place.setEnabled(false);
        }
        
    }//GEN-LAST:event_DistrictKeyTyped

    private void DivisionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DivisionKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_DivisionKeyReleased

    private void PlaceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PlaceKeyReleased
        // TODO add your handling code here:
        if(!"".equals(division.getText())){
            place.setText(JDBCConnection.SearchPlace(Place.getText()));
            if("".equals(place.getText())){
                PlaceDescription.setText("");
                Select.setEnabled(false);
            }
            else{
                PlaceDescription.setText(JDBCConnection.SearchPlaceDescription(place.getText()));
                
                Select.setEnabled(true);
            }
        }
        else if(!"".equals(district.getText())){
            place.setText(JDBCConnection.SearchPlace(Place.getText(),district.getText()));
            if("".equals(place.getText())){
                PlaceDescription.setText("");
                Select.setEnabled(false);
            }
            else{
                PlaceDescription.setText(JDBCConnection.SearchPlaceDescription(place.getText()));
                Select.setEnabled(true);
            }
        }
        else if(!"".equals(district.getText())){
            place.setText(JDBCConnection.SearchPlace(Place.getText(),district.getText(),division.getText()));
            if("".equals(place.getText())){
                PlaceDescription.setText("");
                Select.setEnabled(false);
            }
            else{
                PlaceDescription.setText(JDBCConnection.SearchPlaceDescription(place.getText()));
                Select.setEnabled(true);
            }
        }
    }//GEN-LAST:event_PlaceKeyReleased

    private void DivisionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DivisionKeyTyped
        // TODO add your handling code here:
        division.setText(JDBCConnection.SearchDivision(Division.getText()));
        if(!"".equals(division.getText())){
            District.setEnabled(true);
        }
        else{
            District.setEnabled(false);
        }
    }//GEN-LAST:event_DivisionKeyTyped

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        // TODO add your handling code here:
        PlaceList pl = new PlaceList();
        pl.setVisible(true);
    }//GEN-LAST:event_ViewActionPerformed

    private void SelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectActionPerformed
        // TODO add your handling code here:
        SADProject.ChosenPlace= place.getText();
        this.setVisible(false);
    }//GEN-LAST:event_SelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Places.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Places.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Places.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Places.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Places().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JTextField District;
    private javax.swing.JTextField Division;
    private javax.swing.JTextField Place;
    private javax.swing.JLabel PlaceDescription;
    private javax.swing.JButton Select;
    private javax.swing.JLabel Title1;
    private javax.swing.JButton View;
    private javax.swing.JLabel district;
    private javax.swing.JLabel division;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel place;
    // End of variables declaration//GEN-END:variables
}
