/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sadproject;

/**
 *
 * @author Homepc
 */
public class Transport extends javax.swing.JFrame {
    int transportType = 0;
    /**
     * Creates new form Transport
     */
    public Transport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Bus = new javax.swing.JRadioButton();
        Train = new javax.swing.JRadioButton();
        Plane = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        Title2 = new javax.swing.JLabel();
        budget = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(376, 430));
        getContentPane().setLayout(null);

        jLayeredPane1.setBackground(new java.awt.Color(51, 255, 204));

        buttonGroup1.add(Bus);
        Bus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Bus.setSelected(true);
        Bus.setText("Bus");
        Bus.setOpaque(false);
        Bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusActionPerformed(evt);
            }
        });

        buttonGroup1.add(Train);
        Train.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Train.setText("Train");
        Train.setOpaque(false);
        Train.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainActionPerformed(evt);
            }
        });

        buttonGroup1.add(Plane);
        Plane.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Plane.setText("Plane");
        Plane.setOpaque(false);
        Plane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaneActionPerformed(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Title2.setFont(new java.awt.Font("Poor Richard", 0, 36)); // NOI18N
        Title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title2.setText("EASY TOUR");

        budget.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        budget.setText("Budget Unavailable");

        jLayeredPane1.setLayer(Bus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Train, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Plane, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Title2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(budget, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Title2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Train, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Bus, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Plane, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(budget, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Title2)
                .addGap(60, 60, 60)
                .addComponent(Bus)
                .addGap(18, 18, 18)
                .addComponent(Train)
                .addGap(18, 18, 18)
                .addComponent(Plane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(budget, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(1, 0, 380, 400);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sadproject/button.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 376, 397);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaneActionPerformed
        // TODO add your handling code here:
        transportType = 2;
        int Budget=(JDBCConnection.getFare(JDBCConnection.SearchPlaceID(SADProject.ChosenPlace), transportType));
        if(Budget>0){
            SADProject.TransportBudget=Budget;
            budget.setText(Integer.toString(Budget));
        }
    }//GEN-LAST:event_PlaneActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(Bus.isSelected())
            transportType=0;
        else if(Train.isSelected()){
            transportType=1;
        }
        else
            transportType=2;
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusActionPerformed
        // TODO add your handling code here:
        transportType =0;
        int Budget=(JDBCConnection.getFare(JDBCConnection.SearchPlaceID(SADProject.ChosenPlace), transportType));
        if(Budget>0){
            SADProject.TransportBudget=Budget;
            budget.setText(Integer.toString(Budget));
        }
    }//GEN-LAST:event_BusActionPerformed

    private void TrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainActionPerformed
        // TODO add your handling code here:
        transportType = 1;
        int Budget=(JDBCConnection.getFare(JDBCConnection.SearchPlaceID(SADProject.ChosenPlace), transportType));
        if(Budget>0){
            SADProject.TransportBudget=Budget;
            budget.setText(Integer.toString(Budget));
        }
    }//GEN-LAST:event_TrainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Bus;
    private javax.swing.JRadioButton Plane;
    private javax.swing.JLabel Title2;
    private javax.swing.JRadioButton Train;
    private javax.swing.JLabel budget;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
